// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: query.proto

package querypb

import (
	segmentpb "github.com/berserkdb/berserk-client-go/proto/segmentpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_BOOL        ColumnType = 1
	ColumnType_COLUMN_TYPE_INT32       ColumnType = 2
	ColumnType_COLUMN_TYPE_INT64       ColumnType = 3
	ColumnType_COLUMN_TYPE_DOUBLE      ColumnType = 4
	ColumnType_COLUMN_TYPE_STRING      ColumnType = 5
	ColumnType_COLUMN_TYPE_DATETIME    ColumnType = 6
	ColumnType_COLUMN_TYPE_TIMESPAN    ColumnType = 7
	ColumnType_COLUMN_TYPE_GUID        ColumnType = 8
	ColumnType_COLUMN_TYPE_DYNAMIC     ColumnType = 9
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_BOOL",
		2: "COLUMN_TYPE_INT32",
		3: "COLUMN_TYPE_INT64",
		4: "COLUMN_TYPE_DOUBLE",
		5: "COLUMN_TYPE_STRING",
		6: "COLUMN_TYPE_DATETIME",
		7: "COLUMN_TYPE_TIMESPAN",
		8: "COLUMN_TYPE_GUID",
		9: "COLUMN_TYPE_DYNAMIC",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_BOOL":        1,
		"COLUMN_TYPE_INT32":       2,
		"COLUMN_TYPE_INT64":       3,
		"COLUMN_TYPE_DOUBLE":      4,
		"COLUMN_TYPE_STRING":      5,
		"COLUMN_TYPE_DATETIME":    6,
		"COLUMN_TYPE_TIMESPAN":    7,
		"COLUMN_TYPE_GUID":        8,
		"COLUMN_TYPE_DYNAMIC":     9,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Since         string                 `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ExecuteQueryRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *ExecuteQueryRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// A single frame in the stream of results for a query.
type ExecuteQueryResultFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecuteQueryResultFrame_Schema
	//	*ExecuteQueryResultFrame_Batch
	//	*ExecuteQueryResultFrame_Done
	//	*ExecuteQueryResultFrame_Progress
	//	*ExecuteQueryResultFrame_Error
	//	*ExecuteQueryResultFrame_Metadata
	Payload       isExecuteQueryResultFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResultFrame) Reset() {
	*x = ExecuteQueryResultFrame{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResultFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResultFrame) ProtoMessage() {}

func (x *ExecuteQueryResultFrame) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResultFrame.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResultFrame) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryResultFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteQueryResultFrame) GetPayload() isExecuteQueryResultFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetSchema() *TableSchema {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetBatch() *RowBatch {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetDone() *Completion {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteQueryResultFrame) GetMetadata() *ResultMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ExecuteQueryResultFrame_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isExecuteQueryResultFrame_Payload interface {
	isExecuteQueryResultFrame_Payload()
}

type ExecuteQueryResultFrame_Schema struct {
	// TableSchema contains the schema of one table in the results and will always be
	// sent before the associated RowBatches.
	Schema *TableSchema `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

type ExecuteQueryResultFrame_Batch struct {
	// RowBatch contains the rows. Note that each RowBatch belongs to a result iteration
	// and for every new result iteration, the old set of RowBatches should be discarded.
	// We need this setup of a result set of multiple rowbatches to avoid hitting the 4MB
	// limit in gRPC messages.
	Batch *RowBatch `protobuf:"bytes,3,opt,name=batch,proto3,oneof"`
}

type ExecuteQueryResultFrame_Done struct {
	// If done is sent, then this stream can be closed and no more events will be sent.
	// TODO: We need to be able to signal that a result iteration is done. We should use completion for that.
	Done *Completion `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

type ExecuteQueryResultFrame_Progress struct {
	// / Aux events for progress, etc.
	// progress contains the progress since the last progress was sent.
	Progress *Progress `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

type ExecuteQueryResultFrame_Error struct {
	// error indicates that some error happened that impacted the result set.
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ExecuteQueryResultFrame_Metadata struct {
	// metadata carries warnings or partial failures for the current result set.
	Metadata *ResultMetadata `protobuf:"bytes,7,opt,name=metadata,proto3,oneof"` // TODO: Add healthcheck frame
}

func (*ExecuteQueryResultFrame_Schema) isExecuteQueryResultFrame_Payload() {}

func (*ExecuteQueryResultFrame_Batch) isExecuteQueryResultFrame_Payload() {}

func (*ExecuteQueryResultFrame_Done) isExecuteQueryResultFrame_Payload() {}

func (*ExecuteQueryResultFrame_Progress) isExecuteQueryResultFrame_Payload() {}

func (*ExecuteQueryResultFrame_Error) isExecuteQueryResultFrame_Payload() {}

func (*ExecuteQueryResultFrame_Metadata) isExecuteQueryResultFrame_Payload() {}

type TableSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*Column              `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *TableSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSchema) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ColumnType             `protobuf:"varint,2,opt,name=type,proto3,enum=query.ColumnType" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *Column) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type RowBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table_name referes to the name of the table as specified in a QueryTableSchema.
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// result_iteration_id is an opaque string that identifies a specific result iteration.
	// Whenever a new result iteration starts, all previous rows should be discarded. Thus
	// a result iteration is a complete set of rows for a query.
	ResultIterationId string `protobuf:"bytes,2,opt,name=result_iteration_id,json=resultIterationId,proto3" json:"result_iteration_id,omitempty"`
	// ValueRow contains rows in this batch.
	Rows []*ValueRow `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	// True when this is the last batch for this result_iteration_id.
	// UI should only render complete iterations (where is_iteration_complete=true),
	// except for the first batch which can be shown immediately for fast feedback.
	IsIterationComplete bool `protobuf:"varint,4,opt,name=is_iteration_complete,json=isIterationComplete,proto3" json:"is_iteration_complete,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RowBatch) Reset() {
	*x = RowBatch{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowBatch) ProtoMessage() {}

func (x *RowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowBatch.ProtoReflect.Descriptor instead.
func (*RowBatch) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *RowBatch) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *RowBatch) GetResultIterationId() string {
	if x != nil {
		return x.ResultIterationId
	}
	return ""
}

func (x *RowBatch) GetRows() []*ValueRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *RowBatch) GetIsIterationComplete() bool {
	if x != nil {
		return x.IsIterationComplete
	}
	return false
}

type ValueRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values contains the values for this row. The order of values matches the order of columns
	// in the QueryTableSchema for the table this row belongs to.
	Values        []*segmentpb.TTDynamic `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueRow) Reset() {
	*x = ValueRow{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRow) ProtoMessage() {}

func (x *ValueRow) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRow.ProtoReflect.Descriptor instead.
func (*ValueRow) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *ValueRow) GetValues() []*segmentpb.TTDynamic {
	if x != nil {
		return x.Values
	}
	return nil
}

type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Execution statistics
	RowsProcessed      uint64 `protobuf:"varint,1,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	ChunksTotal        uint64 `protobuf:"varint,2,opt,name=chunks_total,json=chunksTotal,proto3" json:"chunks_total,omitempty"`
	ChunksScanned      uint64 `protobuf:"varint,3,opt,name=chunks_scanned,json=chunksScanned,proto3" json:"chunks_scanned,omitempty"`
	ChunksSkippedRange uint64 `protobuf:"varint,4,opt,name=chunks_skipped_range,json=chunksSkippedRange,proto3" json:"chunks_skipped_range,omitempty"`
	ChunksSkippedBloom uint64 `protobuf:"varint,5,opt,name=chunks_skipped_bloom,json=chunksSkippedBloom,proto3" json:"chunks_skipped_bloom,omitempty"`
	ChunksSkippedShar  uint64 `protobuf:"varint,6,opt,name=chunks_skipped_shar,json=chunksSkippedShar,proto3" json:"chunks_skipped_shar,omitempty"`
	PredicateChecks    uint64 `protobuf:"varint,7,opt,name=predicate_checks,json=predicateChecks,proto3" json:"predicate_checks,omitempty"`
	// Field 8 removed (was bloom_checks - dead code)
	ShortCircuitCompletion     bool   `protobuf:"varint,9,opt,name=short_circuit_completion,json=shortCircuitCompletion,proto3" json:"short_circuit_completion,omitempty"`
	ChunkScannedRawBodySize    uint64 `protobuf:"varint,10,opt,name=chunk_scanned_raw_body_size,json=chunkScannedRawBodySize,proto3" json:"chunk_scanned_raw_body_size,omitempty"`
	ChunkSkippedRawBodySize    uint64 `protobuf:"varint,11,opt,name=chunk_skipped_raw_body_size,json=chunkSkippedRawBodySize,proto3" json:"chunk_skipped_raw_body_size,omitempty"`
	ChunkSkippedCompressedSize uint64 `protobuf:"varint,12,opt,name=chunk_skipped_compressed_size,json=chunkSkippedCompressedSize,proto3" json:"chunk_skipped_compressed_size,omitempty"`
	ChunkScanTimeNanos         uint64 `protobuf:"varint,13,opt,name=chunk_scan_time_nanos,json=chunkScanTimeNanos,proto3" json:"chunk_scan_time_nanos,omitempty"`
	QueryTimeNanos             uint64 `protobuf:"varint,14,opt,name=query_time_nanos,json=queryTimeNanos,proto3" json:"query_time_nanos,omitempty"`
	ChunkScannedCompressedSize uint64 `protobuf:"varint,15,opt,name=chunk_scanned_compressed_size,json=chunkScannedCompressedSize,proto3" json:"chunk_scanned_compressed_size,omitempty"`
	// Bin progress for queries using bin() on numeric or time fields
	BinProgress *BinProgress `protobuf:"bytes,16,opt,name=bin_progress,json=binProgress,proto3,oneof" json:"bin_progress,omitempty"`
	// Time spent waiting in queue before execution started (nanoseconds).
	// Present when the query was queued due to concurrent query limits.
	QueueWaitNanos *uint64 `protobuf:"varint,17,opt,name=queue_wait_nanos,json=queueWaitNanos,proto3,oneof" json:"queue_wait_nanos,omitempty"`
	// Planning progress during segment processing phase.
	// Present during planning, None after planning completes.
	PlanningProgress *PlanningProgress `protobuf:"bytes,18,opt,name=planning_progress,json=planningProgress,proto3,oneof" json:"planning_progress,omitempty"`
	// Total bytes of BLOM chunks evaluated during bloom filtering.
	BloomFilterBytes uint64 `protobuf:"varint,19,opt,name=bloom_filter_bytes,json=bloomFilterBytes,proto3" json:"bloom_filter_bytes,omitempty"`
	// Wall-clock time spent in merge+delivery across all query threads (nanoseconds).
	MergeTimeNanos uint64 `protobuf:"varint,20,opt,name=merge_time_nanos,json=mergeTimeNanos,proto3" json:"merge_time_nanos,omitempty"`
	// Chunks scanned that yielded zero rows passing filters (false positives from pre-filtering).
	ChunksEmptyScan uint64 `protobuf:"varint,21,opt,name=chunks_empty_scan,json=chunksEmptyScan,proto3" json:"chunks_empty_scan,omitempty"`
	// Chunks that passed pre-filters but failed during row processing (e.g. type conversion error).
	ChunksErrored uint64 `protobuf:"varint,22,opt,name=chunks_errored,json=chunksErrored,proto3" json:"chunks_errored,omitempty"`
	// Chunks skipped because required input fields were absent from the chunk.
	ChunksSkippedRequiredFields uint64 `protobuf:"varint,23,opt,name=chunks_skipped_required_fields,json=chunksSkippedRequiredFields,proto3" json:"chunks_skipped_required_fields,omitempty"`
	// Extended per-operator diagnostics in a stable key/value envelope.
	OperatorDiagnostics []*OperatorDiagnostics `protobuf:"bytes,24,rep,name=operator_diagnostics,json=operatorDiagnostics,proto3" json:"operator_diagnostics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetRowsProcessed() uint64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *Progress) GetChunksTotal() uint64 {
	if x != nil {
		return x.ChunksTotal
	}
	return 0
}

func (x *Progress) GetChunksScanned() uint64 {
	if x != nil {
		return x.ChunksScanned
	}
	return 0
}

func (x *Progress) GetChunksSkippedRange() uint64 {
	if x != nil {
		return x.ChunksSkippedRange
	}
	return 0
}

func (x *Progress) GetChunksSkippedBloom() uint64 {
	if x != nil {
		return x.ChunksSkippedBloom
	}
	return 0
}

func (x *Progress) GetChunksSkippedShar() uint64 {
	if x != nil {
		return x.ChunksSkippedShar
	}
	return 0
}

func (x *Progress) GetPredicateChecks() uint64 {
	if x != nil {
		return x.PredicateChecks
	}
	return 0
}

func (x *Progress) GetShortCircuitCompletion() bool {
	if x != nil {
		return x.ShortCircuitCompletion
	}
	return false
}

func (x *Progress) GetChunkScannedRawBodySize() uint64 {
	if x != nil {
		return x.ChunkScannedRawBodySize
	}
	return 0
}

func (x *Progress) GetChunkSkippedRawBodySize() uint64 {
	if x != nil {
		return x.ChunkSkippedRawBodySize
	}
	return 0
}

func (x *Progress) GetChunkSkippedCompressedSize() uint64 {
	if x != nil {
		return x.ChunkSkippedCompressedSize
	}
	return 0
}

func (x *Progress) GetChunkScanTimeNanos() uint64 {
	if x != nil {
		return x.ChunkScanTimeNanos
	}
	return 0
}

func (x *Progress) GetQueryTimeNanos() uint64 {
	if x != nil {
		return x.QueryTimeNanos
	}
	return 0
}

func (x *Progress) GetChunkScannedCompressedSize() uint64 {
	if x != nil {
		return x.ChunkScannedCompressedSize
	}
	return 0
}

func (x *Progress) GetBinProgress() *BinProgress {
	if x != nil {
		return x.BinProgress
	}
	return nil
}

func (x *Progress) GetQueueWaitNanos() uint64 {
	if x != nil && x.QueueWaitNanos != nil {
		return *x.QueueWaitNanos
	}
	return 0
}

func (x *Progress) GetPlanningProgress() *PlanningProgress {
	if x != nil {
		return x.PlanningProgress
	}
	return nil
}

func (x *Progress) GetBloomFilterBytes() uint64 {
	if x != nil {
		return x.BloomFilterBytes
	}
	return 0
}

func (x *Progress) GetMergeTimeNanos() uint64 {
	if x != nil {
		return x.MergeTimeNanos
	}
	return 0
}

func (x *Progress) GetChunksEmptyScan() uint64 {
	if x != nil {
		return x.ChunksEmptyScan
	}
	return 0
}

func (x *Progress) GetChunksErrored() uint64 {
	if x != nil {
		return x.ChunksErrored
	}
	return 0
}

func (x *Progress) GetChunksSkippedRequiredFields() uint64 {
	if x != nil {
		return x.ChunksSkippedRequiredFields
	}
	return 0
}

func (x *Progress) GetOperatorDiagnostics() []*OperatorDiagnostics {
	if x != nil {
		return x.OperatorDiagnostics
	}
	return nil
}

type OperatorDiagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	OperatorId    uint32                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Values        []*KeyValue            `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorDiagnostics) Reset() {
	*x = OperatorDiagnostics{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorDiagnostics) ProtoMessage() {}

func (x *OperatorDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorDiagnostics.ProtoReflect.Descriptor instead.
func (*OperatorDiagnostics) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *OperatorDiagnostics) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperatorDiagnostics) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *OperatorDiagnostics) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Progress information for the planning phase.
// During planning, workers process segments (loading MIMX, applying filters,
// computing chunk/slice overlaps). This tracks that progress.
type PlanningProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of segments that have completed planning across all workers.
	SegmentsDone uint64 `protobuf:"varint,1,opt,name=segments_done,json=segmentsDone,proto3" json:"segments_done,omitempty"`
	// Total number of segments to process across all workers.
	SegmentsTotal uint64 `protobuf:"varint,2,opt,name=segments_total,json=segmentsTotal,proto3" json:"segments_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanningProgress) Reset() {
	*x = PlanningProgress{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanningProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanningProgress) ProtoMessage() {}

func (x *PlanningProgress) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanningProgress.ProtoReflect.Descriptor instead.
func (*PlanningProgress) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *PlanningProgress) GetSegmentsDone() uint64 {
	if x != nil {
		return x.SegmentsDone
	}
	return 0
}

func (x *PlanningProgress) GetSegmentsTotal() uint64 {
	if x != nil {
		return x.SegmentsTotal
	}
	return 0
}

// Progress information for bin() aggregations.
// Reports completion progress per bin for queries using `summarize ... by bin(field, span)`.
type BinProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start value of the first bin (the bin boundary).
	// Bin N covers range [first_bin_start + N * bin_span, first_bin_start + (N+1) * bin_span)
	FirstBinStart int64 `protobuf:"zigzag64,1,opt,name=first_bin_start,json=firstBinStart,proto3" json:"first_bin_start,omitempty"`
	// Span (width) of each bin.
	BinSpan uint64 `protobuf:"varint,2,opt,name=bin_span,json=binSpan,proto3" json:"bin_span,omitempty"`
	// Completion percentage (0-100) for each bin.
	// Index i corresponds to bin i. Value 100 means all workers have reported.
	CompletionPercentages []byte `protobuf:"bytes,3,opt,name=completion_percentages,json=completionPercentages,proto3" json:"completion_percentages,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BinProgress) Reset() {
	*x = BinProgress{}
	mi := &file_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinProgress) ProtoMessage() {}

func (x *BinProgress) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinProgress.ProtoReflect.Descriptor instead.
func (*BinProgress) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{10}
}

func (x *BinProgress) GetFirstBinStart() int64 {
	if x != nil {
		return x.FirstBinStart
	}
	return 0
}

func (x *BinProgress) GetBinSpan() uint64 {
	if x != nil {
		return x.BinSpan
	}
	return 0
}

func (x *BinProgress) GetCompletionPercentages() []byte {
	if x != nil {
		return x.CompletionPercentages
	}
	return nil
}

type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{11}
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code - discriminator for error_details (e.g., "UnknownFunction", "TypeMismatch")
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Brief title
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Support ticket ID for tracking
	SupportTicketId string `protobuf:"bytes,4,opt,name=support_ticket_id,json=supportTicketId,proto3" json:"support_ticket_id,omitempty"`
	// Pre-rendered error message with span annotations (for simple clients)
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Source location
	Location *Location `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	// JSON-encoded error details (actual KustoError for reconstruction)
	Details       string `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{12}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Error) GetSupportTicketId() string {
	if x != nil {
		return x.SupportTicketId
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Source code location
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartByte     uint32                 `protobuf:"varint,1,opt,name=start_byte,json=startByte,proto3" json:"start_byte,omitempty"`
	EndByte       uint32                 `protobuf:"varint,2,opt,name=end_byte,json=endByte,proto3" json:"end_byte,omitempty"`
	StartLine     uint32                 `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartColumn   uint32                 `protobuf:"varint,4,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndLine       uint32                 `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     uint32                 `protobuf:"varint,6,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{13}
}

func (x *Location) GetStartByte() uint32 {
	if x != nil {
		return x.StartByte
	}
	return 0
}

func (x *Location) GetEndByte() uint32 {
	if x != nil {
		return x.EndByte
	}
	return 0
}

func (x *Location) GetStartLine() uint32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Location) GetStartColumn() uint32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *Location) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Location) GetEndColumn() uint32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

type PartialFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentIds    []string               `protobuf:"bytes,1,rep,name=segment_ids,json=segmentIds,proto3" json:"segment_ids,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialFailure) Reset() {
	*x = PartialFailure{}
	mi := &file_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialFailure) ProtoMessage() {}

func (x *PartialFailure) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialFailure.ProtoReflect.Descriptor instead.
func (*PartialFailure) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{14}
}

func (x *PartialFailure) GetSegmentIds() []string {
	if x != nil {
		return x.SegmentIds
	}
	return nil
}

func (x *PartialFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Visualization metadata from render operator
type VisualizationMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Visualization type: "table", "timechart", "linechart", etc.
	VisualizationType *string           `protobuf:"bytes,1,opt,name=visualization_type,json=visualizationType,proto3,oneof" json:"visualization_type,omitempty"`
	Properties        map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VisualizationMetadata) Reset() {
	*x = VisualizationMetadata{}
	mi := &file_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizationMetadata) ProtoMessage() {}

func (x *VisualizationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizationMetadata.ProtoReflect.Descriptor instead.
func (*VisualizationMetadata) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{15}
}

func (x *VisualizationMetadata) GetVisualizationType() string {
	if x != nil && x.VisualizationType != nil {
		return *x.VisualizationType
	}
	return ""
}

func (x *VisualizationMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ResultMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PartialFailures []*PartialFailure      `protobuf:"bytes,1,rep,name=partial_failures,json=partialFailures,proto3" json:"partial_failures,omitempty"`
	// Visualization metadata from render operator (if present)
	Visualization *VisualizationMetadata `protobuf:"bytes,2,opt,name=visualization,proto3,oneof" json:"visualization,omitempty"`
	// Execution warnings (limits hit, etc.)
	Warnings      []*QueryWarning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultMetadata) Reset() {
	*x = ResultMetadata{}
	mi := &file_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMetadata) ProtoMessage() {}

func (x *ResultMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMetadata.ProtoReflect.Descriptor instead.
func (*ResultMetadata) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{16}
}

func (x *ResultMetadata) GetPartialFailures() []*PartialFailure {
	if x != nil {
		return x.PartialFailures
	}
	return nil
}

func (x *ResultMetadata) GetVisualization() *VisualizationMetadata {
	if x != nil {
		return x.Visualization
	}
	return nil
}

func (x *ResultMetadata) GetWarnings() []*QueryWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Warning produced during query execution (e.g., limit was hit).
type QueryWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator ID for source correlation
	OperatorId uint32 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	// Branch index for fork queries (0 = not a fork)
	BranchIndex *uint32 `protobuf:"varint,2,opt,name=branch_index,json=branchIndex,proto3,oneof" json:"branch_index,omitempty"`
	// Warning kind discriminator (e.g., "SummarizeMemoryLimit")
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Source location (resolved from span registry)
	Location *Location `protobuf:"bytes,4,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Human-readable message
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Structured details as JSON
	Details       string `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWarning) Reset() {
	*x = QueryWarning{}
	mi := &file_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWarning) ProtoMessage() {}

func (x *QueryWarning) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWarning.ProtoReflect.Descriptor instead.
func (*QueryWarning) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryWarning) GetOperatorId() uint32 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *QueryWarning) GetBranchIndex() uint32 {
	if x != nil && x.BranchIndex != nil {
		return *x.BranchIndex
	}
	return 0
}

func (x *QueryWarning) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *QueryWarning) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *QueryWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryWarning) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x05query\x1a\x13dynamic_value.proto\"s\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05since\x18\x02 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x03 \x01(\tR\x05until\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\"\xcd\x02\n" +
	"\x17ExecuteQueryResultFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x06schema\x18\x02 \x01(\v2\x12.query.TableSchemaH\x00R\x06schema\x12'\n" +
	"\x05batch\x18\x03 \x01(\v2\x0f.query.RowBatchH\x00R\x05batch\x12'\n" +
	"\x04done\x18\x05 \x01(\v2\x11.query.CompletionH\x00R\x04done\x12-\n" +
	"\bprogress\x18\x04 \x01(\v2\x0f.query.ProgressH\x00R\bprogress\x12$\n" +
	"\x05error\x18\x06 \x01(\v2\f.query.ErrorH\x00R\x05error\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x15.query.ResultMetadataH\x00R\bmetadataB\t\n" +
	"\apayload\"J\n" +
	"\vTableSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\acolumns\x18\x02 \x03(\v2\r.query.ColumnR\acolumns\"_\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.query.ColumnTypeR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\"\xb2\x01\n" +
	"\bRowBatch\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12.\n" +
	"\x13result_iteration_id\x18\x02 \x01(\tR\x11resultIterationId\x12#\n" +
	"\x04rows\x18\x03 \x03(\v2\x0f.query.ValueRowR\x04rows\x122\n" +
	"\x15is_iteration_complete\x18\x04 \x01(\bR\x13isIterationComplete\"<\n" +
	"\bValueRow\x120\n" +
	"\x06values\x18\x01 \x03(\v2\x18.segment_files.TTDynamicR\x06values\"\x84\n" +
	"\n" +
	"\bProgress\x12%\n" +
	"\x0erows_processed\x18\x01 \x01(\x04R\rrowsProcessed\x12!\n" +
	"\fchunks_total\x18\x02 \x01(\x04R\vchunksTotal\x12%\n" +
	"\x0echunks_scanned\x18\x03 \x01(\x04R\rchunksScanned\x120\n" +
	"\x14chunks_skipped_range\x18\x04 \x01(\x04R\x12chunksSkippedRange\x120\n" +
	"\x14chunks_skipped_bloom\x18\x05 \x01(\x04R\x12chunksSkippedBloom\x12.\n" +
	"\x13chunks_skipped_shar\x18\x06 \x01(\x04R\x11chunksSkippedShar\x12)\n" +
	"\x10predicate_checks\x18\a \x01(\x04R\x0fpredicateChecks\x128\n" +
	"\x18short_circuit_completion\x18\t \x01(\bR\x16shortCircuitCompletion\x12<\n" +
	"\x1bchunk_scanned_raw_body_size\x18\n" +
	" \x01(\x04R\x17chunkScannedRawBodySize\x12<\n" +
	"\x1bchunk_skipped_raw_body_size\x18\v \x01(\x04R\x17chunkSkippedRawBodySize\x12A\n" +
	"\x1dchunk_skipped_compressed_size\x18\f \x01(\x04R\x1achunkSkippedCompressedSize\x121\n" +
	"\x15chunk_scan_time_nanos\x18\r \x01(\x04R\x12chunkScanTimeNanos\x12(\n" +
	"\x10query_time_nanos\x18\x0e \x01(\x04R\x0equeryTimeNanos\x12A\n" +
	"\x1dchunk_scanned_compressed_size\x18\x0f \x01(\x04R\x1achunkScannedCompressedSize\x12:\n" +
	"\fbin_progress\x18\x10 \x01(\v2\x12.query.BinProgressH\x00R\vbinProgress\x88\x01\x01\x12-\n" +
	"\x10queue_wait_nanos\x18\x11 \x01(\x04H\x01R\x0equeueWaitNanos\x88\x01\x01\x12I\n" +
	"\x11planning_progress\x18\x12 \x01(\v2\x17.query.PlanningProgressH\x02R\x10planningProgress\x88\x01\x01\x12,\n" +
	"\x12bloom_filter_bytes\x18\x13 \x01(\x04R\x10bloomFilterBytes\x12(\n" +
	"\x10merge_time_nanos\x18\x14 \x01(\x04R\x0emergeTimeNanos\x12*\n" +
	"\x11chunks_empty_scan\x18\x15 \x01(\x04R\x0fchunksEmptyScan\x12%\n" +
	"\x0echunks_errored\x18\x16 \x01(\x04R\rchunksErrored\x12C\n" +
	"\x1echunks_skipped_required_fields\x18\x17 \x01(\x04R\x1bchunksSkippedRequiredFields\x12M\n" +
	"\x14operator_diagnostics\x18\x18 \x03(\v2\x1a.query.OperatorDiagnosticsR\x13operatorDiagnosticsB\x0f\n" +
	"\r_bin_progressB\x13\n" +
	"\x11_queue_wait_nanosB\x14\n" +
	"\x12_planning_progress\"s\n" +
	"\x13OperatorDiagnostics\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\rR\n" +
	"operatorId\x12'\n" +
	"\x06values\x18\x03 \x03(\v2\x0f.query.KeyValueR\x06values\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"^\n" +
	"\x10PlanningProgress\x12#\n" +
	"\rsegments_done\x18\x01 \x01(\x04R\fsegmentsDone\x12%\n" +
	"\x0esegments_total\x18\x02 \x01(\x04R\rsegmentsTotal\"\x87\x01\n" +
	"\vBinProgress\x12&\n" +
	"\x0ffirst_bin_start\x18\x01 \x01(\x12R\rfirstBinStart\x12\x19\n" +
	"\bbin_span\x18\x02 \x01(\x04R\abinSpan\x125\n" +
	"\x16completion_percentages\x18\x03 \x01(\fR\x15completionPercentages\"\f\n" +
	"\n" +
	"Completion\"\xbe\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\x11support_ticket_id\x18\x04 \x01(\tR\x0fsupportTicketId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12+\n" +
	"\blocation\x18\a \x01(\v2\x0f.query.LocationR\blocation\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\"\xc0\x01\n" +
	"\bLocation\x12\x1d\n" +
	"\n" +
	"start_byte\x18\x01 \x01(\rR\tstartByte\x12\x19\n" +
	"\bend_byte\x18\x02 \x01(\rR\aendByte\x12\x1d\n" +
	"\n" +
	"start_line\x18\x03 \x01(\rR\tstartLine\x12!\n" +
	"\fstart_column\x18\x04 \x01(\rR\vstartColumn\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\rR\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x06 \x01(\rR\tendColumn\"K\n" +
	"\x0ePartialFailure\x12\x1f\n" +
	"\vsegment_ids\x18\x01 \x03(\tR\n" +
	"segmentIds\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xef\x01\n" +
	"\x15VisualizationMetadata\x122\n" +
	"\x12visualization_type\x18\x01 \x01(\tH\x00R\x11visualizationType\x88\x01\x01\x12L\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2,.query.VisualizationMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x15\n" +
	"\x13_visualization_type\"\xde\x01\n" +
	"\x0eResultMetadata\x12@\n" +
	"\x10partial_failures\x18\x01 \x03(\v2\x15.query.PartialFailureR\x0fpartialFailures\x12G\n" +
	"\rvisualization\x18\x02 \x01(\v2\x1c.query.VisualizationMetadataH\x00R\rvisualization\x88\x01\x01\x12/\n" +
	"\bwarnings\x18\x03 \x03(\v2\x13.query.QueryWarningR\bwarningsB\x10\n" +
	"\x0e_visualization\"\xef\x01\n" +
	"\fQueryWarning\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\rR\n" +
	"operatorId\x12&\n" +
	"\fbranch_index\x18\x02 \x01(\rH\x00R\vbranchIndex\x88\x01\x01\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x120\n" +
	"\blocation\x18\x04 \x01(\v2\x0f.query.LocationH\x01R\blocation\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetailsB\x0f\n" +
	"\r_branch_indexB\v\n" +
	"\t_location*\x80\x02\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COLUMN_TYPE_BOOL\x10\x01\x12\x15\n" +
	"\x11COLUMN_TYPE_INT32\x10\x02\x12\x15\n" +
	"\x11COLUMN_TYPE_INT64\x10\x03\x12\x16\n" +
	"\x12COLUMN_TYPE_DOUBLE\x10\x04\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\x05\x12\x18\n" +
	"\x14COLUMN_TYPE_DATETIME\x10\x06\x12\x18\n" +
	"\x14COLUMN_TYPE_TIMESPAN\x10\a\x12\x14\n" +
	"\x10COLUMN_TYPE_GUID\x10\b\x12\x17\n" +
	"\x13COLUMN_TYPE_DYNAMIC\x10\t2\\\n" +
	"\fQueryService\x12L\n" +
	"\fExecuteQuery\x12\x1a.query.ExecuteQueryRequest\x1a\x1e.query.ExecuteQueryResultFrame0\x01B6Z4github.com/berserkdb/berserk-client-go/proto/querypbb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_query_proto_goTypes = []any{
	(ColumnType)(0),                 // 0: query.ColumnType
	(*ExecuteQueryRequest)(nil),     // 1: query.ExecuteQueryRequest
	(*ExecuteQueryResultFrame)(nil), // 2: query.ExecuteQueryResultFrame
	(*TableSchema)(nil),             // 3: query.TableSchema
	(*Column)(nil),                  // 4: query.Column
	(*RowBatch)(nil),                // 5: query.RowBatch
	(*ValueRow)(nil),                // 6: query.ValueRow
	(*Progress)(nil),                // 7: query.Progress
	(*OperatorDiagnostics)(nil),     // 8: query.OperatorDiagnostics
	(*KeyValue)(nil),                // 9: query.KeyValue
	(*PlanningProgress)(nil),        // 10: query.PlanningProgress
	(*BinProgress)(nil),             // 11: query.BinProgress
	(*Completion)(nil),              // 12: query.Completion
	(*Error)(nil),                   // 13: query.Error
	(*Location)(nil),                // 14: query.Location
	(*PartialFailure)(nil),          // 15: query.PartialFailure
	(*VisualizationMetadata)(nil),   // 16: query.VisualizationMetadata
	(*ResultMetadata)(nil),          // 17: query.ResultMetadata
	(*QueryWarning)(nil),            // 18: query.QueryWarning
	nil,                             // 19: query.VisualizationMetadata.PropertiesEntry
	(*segmentpb.TTDynamic)(nil),     // 20: segment_files.TTDynamic
}
var file_query_proto_depIdxs = []int32{
	3,  // 0: query.ExecuteQueryResultFrame.schema:type_name -> query.TableSchema
	5,  // 1: query.ExecuteQueryResultFrame.batch:type_name -> query.RowBatch
	12, // 2: query.ExecuteQueryResultFrame.done:type_name -> query.Completion
	7,  // 3: query.ExecuteQueryResultFrame.progress:type_name -> query.Progress
	13, // 4: query.ExecuteQueryResultFrame.error:type_name -> query.Error
	17, // 5: query.ExecuteQueryResultFrame.metadata:type_name -> query.ResultMetadata
	4,  // 6: query.TableSchema.columns:type_name -> query.Column
	0,  // 7: query.Column.type:type_name -> query.ColumnType
	6,  // 8: query.RowBatch.rows:type_name -> query.ValueRow
	20, // 9: query.ValueRow.values:type_name -> segment_files.TTDynamic
	11, // 10: query.Progress.bin_progress:type_name -> query.BinProgress
	10, // 11: query.Progress.planning_progress:type_name -> query.PlanningProgress
	8,  // 12: query.Progress.operator_diagnostics:type_name -> query.OperatorDiagnostics
	9,  // 13: query.OperatorDiagnostics.values:type_name -> query.KeyValue
	14, // 14: query.Error.location:type_name -> query.Location
	19, // 15: query.VisualizationMetadata.properties:type_name -> query.VisualizationMetadata.PropertiesEntry
	15, // 16: query.ResultMetadata.partial_failures:type_name -> query.PartialFailure
	16, // 17: query.ResultMetadata.visualization:type_name -> query.VisualizationMetadata
	18, // 18: query.ResultMetadata.warnings:type_name -> query.QueryWarning
	14, // 19: query.QueryWarning.location:type_name -> query.Location
	1,  // 20: query.QueryService.ExecuteQuery:input_type -> query.ExecuteQueryRequest
	2,  // 21: query.QueryService.ExecuteQuery:output_type -> query.ExecuteQueryResultFrame
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_query_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteQueryResultFrame_Schema)(nil),
		(*ExecuteQueryResultFrame_Batch)(nil),
		(*ExecuteQueryResultFrame_Done)(nil),
		(*ExecuteQueryResultFrame_Progress)(nil),
		(*ExecuteQueryResultFrame_Error)(nil),
		(*ExecuteQueryResultFrame_Metadata)(nil),
	}
	file_query_proto_msgTypes[6].OneofWrappers = []any{}
	file_query_proto_msgTypes[15].OneofWrappers = []any{}
	file_query_proto_msgTypes[16].OneofWrappers = []any{}
	file_query_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		EnumInfos:         file_query_proto_enumTypes,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
