// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: dynamic_value.proto

package segmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TtStatus int32

const (
	TtStatus_OK                   TtStatus = 0
	TtStatus_BadArg               TtStatus = 1
	TtStatus_InternalError        TtStatus = 2
	TtStatus_InvalidTimeFieldType TtStatus = 3
	TtStatus_MissingTimeField     TtStatus = 4
)

// Enum value maps for TtStatus.
var (
	TtStatus_name = map[int32]string{
		0: "OK",
		1: "BadArg",
		2: "InternalError",
		3: "InvalidTimeFieldType",
		4: "MissingTimeField",
	}
	TtStatus_value = map[string]int32{
		"OK":                   0,
		"BadArg":               1,
		"InternalError":        2,
		"InvalidTimeFieldType": 3,
		"MissingTimeField":     4,
	}
)

func (x TtStatus) Enum() *TtStatus {
	p := new(TtStatus)
	*p = x
	return p
}

func (x TtStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TtStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dynamic_value_proto_enumTypes[0].Descriptor()
}

func (TtStatus) Type() protoreflect.EnumType {
	return &file_dynamic_value_proto_enumTypes[0]
}

func (x TtStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TtStatus.Descriptor instead.
func (TtStatus) EnumDescriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{0}
}

// A dynamic value that can hold various data types
// Maps to the Rust DynamicValue enum
type TTDynamic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TTDynamic_TtNull
	//	*TTDynamic_TtDouble
	//	*TTDynamic_TtLong
	//	*TTDynamic_TtInt
	//	*TTDynamic_TtString
	//	*TTDynamic_TtBool
	//	*TTDynamic_TtTimespan
	//	*TTDynamic_TtTimestamp
	//	*TTDynamic_TtPropertybag
	//	*TTDynamic_TtArray
	Value         isTTDynamic_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTDynamic) Reset() {
	*x = TTDynamic{}
	mi := &file_dynamic_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTDynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTDynamic) ProtoMessage() {}

func (x *TTDynamic) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTDynamic.ProtoReflect.Descriptor instead.
func (*TTDynamic) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{0}
}

func (x *TTDynamic) GetValue() isTTDynamic_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TTDynamic) GetTtNull() bool {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtNull); ok {
			return x.TtNull
		}
	}
	return false
}

func (x *TTDynamic) GetTtDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtDouble); ok {
			return x.TtDouble
		}
	}
	return 0
}

func (x *TTDynamic) GetTtLong() int64 {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtLong); ok {
			return x.TtLong
		}
	}
	return 0
}

func (x *TTDynamic) GetTtInt() int32 {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtInt); ok {
			return x.TtInt
		}
	}
	return 0
}

func (x *TTDynamic) GetTtString() string {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtString); ok {
			return x.TtString
		}
	}
	return ""
}

func (x *TTDynamic) GetTtBool() bool {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtBool); ok {
			return x.TtBool
		}
	}
	return false
}

func (x *TTDynamic) GetTtTimespan() uint64 {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtTimespan); ok {
			return x.TtTimespan
		}
	}
	return 0
}

func (x *TTDynamic) GetTtTimestamp() uint64 {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtTimestamp); ok {
			return x.TtTimestamp
		}
	}
	return 0
}

func (x *TTDynamic) GetTtPropertybag() *TTPropertyBag {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtPropertybag); ok {
			return x.TtPropertybag
		}
	}
	return nil
}

func (x *TTDynamic) GetTtArray() *TTArray {
	if x != nil {
		if x, ok := x.Value.(*TTDynamic_TtArray); ok {
			return x.TtArray
		}
	}
	return nil
}

type isTTDynamic_Value interface {
	isTTDynamic_Value()
}

type TTDynamic_TtNull struct {
	// Null value - using google.protobuf.NullValue would be better
	// but for simplicity using a bool flag
	TtNull bool `protobuf:"varint,1,opt,name=tt_null,json=ttNull,proto3,oneof"`
}

type TTDynamic_TtDouble struct {
	// 64-bit floating point number
	TtDouble float64 `protobuf:"fixed64,2,opt,name=tt_double,json=ttDouble,proto3,oneof"`
}

type TTDynamic_TtLong struct {
	// 64-bit signed integer
	TtLong int64 `protobuf:"varint,3,opt,name=tt_long,json=ttLong,proto3,oneof"`
}

type TTDynamic_TtInt struct {
	// 32-bit signed integer
	TtInt int32 `protobuf:"varint,4,opt,name=tt_int,json=ttInt,proto3,oneof"`
}

type TTDynamic_TtString struct {
	// UTF-8 string
	TtString string `protobuf:"bytes,5,opt,name=tt_string,json=ttString,proto3,oneof"`
}

type TTDynamic_TtBool struct {
	// Boolean value
	TtBool bool `protobuf:"varint,6,opt,name=tt_bool,json=ttBool,proto3,oneof"`
}

type TTDynamic_TtTimespan struct {
	// Timespan in ticks (100-nanosecond intervals)
	TtTimespan uint64 `protobuf:"varint,7,opt,name=tt_timespan,json=ttTimespan,proto3,oneof"`
}

type TTDynamic_TtTimestamp struct {
	// Timestamp in ticks (100-nanosecond intervals)
	TtTimestamp uint64 `protobuf:"varint,10,opt,name=tt_timestamp,json=ttTimestamp,proto3,oneof"`
}

type TTDynamic_TtPropertybag struct {
	// Nested key-value pairs (property bag)
	TtPropertybag *TTPropertyBag `protobuf:"bytes,8,opt,name=tt_propertybag,json=ttPropertybag,proto3,oneof"`
}

type TTDynamic_TtArray struct {
	// Array of dynamic values
	TtArray *TTArray `protobuf:"bytes,9,opt,name=tt_array,json=ttArray,proto3,oneof"`
}

func (*TTDynamic_TtNull) isTTDynamic_Value() {}

func (*TTDynamic_TtDouble) isTTDynamic_Value() {}

func (*TTDynamic_TtLong) isTTDynamic_Value() {}

func (*TTDynamic_TtInt) isTTDynamic_Value() {}

func (*TTDynamic_TtString) isTTDynamic_Value() {}

func (*TTDynamic_TtBool) isTTDynamic_Value() {}

func (*TTDynamic_TtTimespan) isTTDynamic_Value() {}

func (*TTDynamic_TtTimestamp) isTTDynamic_Value() {}

func (*TTDynamic_TtPropertybag) isTTDynamic_Value() {}

func (*TTDynamic_TtArray) isTTDynamic_Value() {}

// Property bag containing key-value pairs
type TTPropertyBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    map[string]*TTDynamic  `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTPropertyBag) Reset() {
	*x = TTPropertyBag{}
	mi := &file_dynamic_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTPropertyBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTPropertyBag) ProtoMessage() {}

func (x *TTPropertyBag) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTPropertyBag.ProtoReflect.Descriptor instead.
func (*TTPropertyBag) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{1}
}

func (x *TTPropertyBag) GetProperties() map[string]*TTDynamic {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Array of dynamic values
type TTArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*TTDynamic           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTArray) Reset() {
	*x = TTArray{}
	mi := &file_dynamic_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTArray) ProtoMessage() {}

func (x *TTArray) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTArray.ProtoReflect.Descriptor instead.
func (*TTArray) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{2}
}

func (x *TTArray) GetValues() []*TTDynamic {
	if x != nil {
		return x.Values
	}
	return nil
}

// A dotted-path scope: a path prefix where dotted keys should be expanded.
// E.g. ["resource", "attributes"] means keys like "service.name" inside
// resource.attributes will be expanded into nested structure.
type DottedPathScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DottedPathScope) Reset() {
	*x = DottedPathScope{}
	mi := &file_dynamic_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DottedPathScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DottedPathScope) ProtoMessage() {}

func (x *DottedPathScope) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DottedPathScope.ProtoReflect.Descriptor instead.
func (*DottedPathScope) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{3}
}

func (x *DottedPathScope) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

// The request to encode a segment file is written like this
type TTEncodeSegmentRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Values                  []*TTPropertyBag       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	ShortcutsForDottedPaths []*DottedPathScope     `protobuf:"bytes,2,rep,name=shortcuts_for_dotted_paths,json=shortcutsForDottedPaths,proto3" json:"shortcuts_for_dotted_paths,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TTEncodeSegmentRequest) Reset() {
	*x = TTEncodeSegmentRequest{}
	mi := &file_dynamic_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTEncodeSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTEncodeSegmentRequest) ProtoMessage() {}

func (x *TTEncodeSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTEncodeSegmentRequest.ProtoReflect.Descriptor instead.
func (*TTEncodeSegmentRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{4}
}

func (x *TTEncodeSegmentRequest) GetValues() []*TTPropertyBag {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *TTEncodeSegmentRequest) GetShortcutsForDottedPaths() []*DottedPathScope {
	if x != nil {
		return x.ShortcutsForDottedPaths
	}
	return nil
}

// The returned value is this
type TTEncodeSegmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatusCode      TtStatus               `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=segment_files.TtStatus" json:"status_code,omitempty"`
	SegmentFileData []byte                 `protobuf:"bytes,2,opt,name=segment_file_data,json=segmentFileData,proto3" json:"segment_file_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TTEncodeSegmentResponse) Reset() {
	*x = TTEncodeSegmentResponse{}
	mi := &file_dynamic_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTEncodeSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTEncodeSegmentResponse) ProtoMessage() {}

func (x *TTEncodeSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTEncodeSegmentResponse.ProtoReflect.Descriptor instead.
func (*TTEncodeSegmentResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{5}
}

func (x *TTEncodeSegmentResponse) GetStatusCode() TtStatus {
	if x != nil {
		return x.StatusCode
	}
	return TtStatus_OK
}

func (x *TTEncodeSegmentResponse) GetSegmentFileData() []byte {
	if x != nil {
		return x.SegmentFileData
	}
	return nil
}

var File_dynamic_value_proto protoreflect.FileDescriptor

const file_dynamic_value_proto_rawDesc = "" +
	"\n" +
	"\x13dynamic_value.proto\x12\rsegment_files\"\x80\x03\n" +
	"\tTTDynamic\x12\x19\n" +
	"\att_null\x18\x01 \x01(\bH\x00R\x06ttNull\x12\x1d\n" +
	"\ttt_double\x18\x02 \x01(\x01H\x00R\bttDouble\x12\x19\n" +
	"\att_long\x18\x03 \x01(\x03H\x00R\x06ttLong\x12\x17\n" +
	"\x06tt_int\x18\x04 \x01(\x05H\x00R\x05ttInt\x12\x1d\n" +
	"\ttt_string\x18\x05 \x01(\tH\x00R\bttString\x12\x19\n" +
	"\att_bool\x18\x06 \x01(\bH\x00R\x06ttBool\x12!\n" +
	"\vtt_timespan\x18\a \x01(\x04H\x00R\n" +
	"ttTimespan\x12#\n" +
	"\ftt_timestamp\x18\n" +
	" \x01(\x04H\x00R\vttTimestamp\x12E\n" +
	"\x0ett_propertybag\x18\b \x01(\v2\x1c.segment_files.TTPropertyBagH\x00R\rttPropertybag\x123\n" +
	"\btt_array\x18\t \x01(\v2\x16.segment_files.TTArrayH\x00R\attArrayB\a\n" +
	"\x05value\"\xb6\x01\n" +
	"\rTTPropertyBag\x12L\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2,.segment_files.TTPropertyBag.PropertiesEntryR\n" +
	"properties\x1aW\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.segment_files.TTDynamicR\x05value:\x028\x01\";\n" +
	"\aTTArray\x120\n" +
	"\x06values\x18\x01 \x03(\v2\x18.segment_files.TTDynamicR\x06values\"%\n" +
	"\x0fDottedPathScope\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\"\xab\x01\n" +
	"\x16TTEncodeSegmentRequest\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.segment_files.TTPropertyBagR\x06values\x12[\n" +
	"\x1ashortcuts_for_dotted_paths\x18\x02 \x03(\v2\x1e.segment_files.DottedPathScopeR\x17shortcutsForDottedPaths\"\x7f\n" +
	"\x17TTEncodeSegmentResponse\x128\n" +
	"\vstatus_code\x18\x01 \x01(\x0e2\x17.segment_files.TtStatusR\n" +
	"statusCode\x12*\n" +
	"\x11segment_file_data\x18\x02 \x01(\fR\x0fsegmentFileData*a\n" +
	"\bTtStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06BadArg\x10\x01\x12\x11\n" +
	"\rInternalError\x10\x02\x12\x18\n" +
	"\x14InvalidTimeFieldType\x10\x03\x12\x14\n" +
	"\x10MissingTimeField\x10\x04B8Z6github.com/berserkdb/berserk-client-go/proto/segmentpbb\x06proto3"

var (
	file_dynamic_value_proto_rawDescOnce sync.Once
	file_dynamic_value_proto_rawDescData []byte
)

func file_dynamic_value_proto_rawDescGZIP() []byte {
	file_dynamic_value_proto_rawDescOnce.Do(func() {
		file_dynamic_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)))
	})
	return file_dynamic_value_proto_rawDescData
}

var file_dynamic_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dynamic_value_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dynamic_value_proto_goTypes = []any{
	(TtStatus)(0),                   // 0: segment_files.TtStatus
	(*TTDynamic)(nil),               // 1: segment_files.TTDynamic
	(*TTPropertyBag)(nil),           // 2: segment_files.TTPropertyBag
	(*TTArray)(nil),                 // 3: segment_files.TTArray
	(*DottedPathScope)(nil),         // 4: segment_files.DottedPathScope
	(*TTEncodeSegmentRequest)(nil),  // 5: segment_files.TTEncodeSegmentRequest
	(*TTEncodeSegmentResponse)(nil), // 6: segment_files.TTEncodeSegmentResponse
	nil,                             // 7: segment_files.TTPropertyBag.PropertiesEntry
}
var file_dynamic_value_proto_depIdxs = []int32{
	2, // 0: segment_files.TTDynamic.tt_propertybag:type_name -> segment_files.TTPropertyBag
	3, // 1: segment_files.TTDynamic.tt_array:type_name -> segment_files.TTArray
	7, // 2: segment_files.TTPropertyBag.properties:type_name -> segment_files.TTPropertyBag.PropertiesEntry
	1, // 3: segment_files.TTArray.values:type_name -> segment_files.TTDynamic
	2, // 4: segment_files.TTEncodeSegmentRequest.values:type_name -> segment_files.TTPropertyBag
	4, // 5: segment_files.TTEncodeSegmentRequest.shortcuts_for_dotted_paths:type_name -> segment_files.DottedPathScope
	0, // 6: segment_files.TTEncodeSegmentResponse.status_code:type_name -> segment_files.TtStatus
	1, // 7: segment_files.TTPropertyBag.PropertiesEntry.value:type_name -> segment_files.TTDynamic
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dynamic_value_proto_init() }
func file_dynamic_value_proto_init() {
	if File_dynamic_value_proto != nil {
		return
	}
	file_dynamic_value_proto_msgTypes[0].OneofWrappers = []any{
		(*TTDynamic_TtNull)(nil),
		(*TTDynamic_TtDouble)(nil),
		(*TTDynamic_TtLong)(nil),
		(*TTDynamic_TtInt)(nil),
		(*TTDynamic_TtString)(nil),
		(*TTDynamic_TtBool)(nil),
		(*TTDynamic_TtTimespan)(nil),
		(*TTDynamic_TtTimestamp)(nil),
		(*TTDynamic_TtPropertybag)(nil),
		(*TTDynamic_TtArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynamic_value_proto_goTypes,
		DependencyIndexes: file_dynamic_value_proto_depIdxs,
		EnumInfos:         file_dynamic_value_proto_enumTypes,
		MessageInfos:      file_dynamic_value_proto_msgTypes,
	}.Build()
	File_dynamic_value_proto = out.File
	file_dynamic_value_proto_goTypes = nil
	file_dynamic_value_proto_depIdxs = nil
}
