// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: common_api.proto

package berserkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wire-format identifier for a database. Callers send either the UUID
// (`id`) or the human-readable `name`. The server resolves `name` to an
// id once per request via the metadata service. Empty oneof / empty
// strings are rejected with `InvalidArgument` at every boundary that
// accepts a `DatabaseRef`.
type DatabaseRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DatabaseRef_Id
	//	*DatabaseRef_Name
	Identifier    isDatabaseRef_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseRef) Reset() {
	*x = DatabaseRef{}
	mi := &file_common_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseRef) ProtoMessage() {}

func (x *DatabaseRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseRef.ProtoReflect.Descriptor instead.
func (*DatabaseRef) Descriptor() ([]byte, []int) {
	return file_common_api_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseRef) GetIdentifier() isDatabaseRef_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DatabaseRef) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*DatabaseRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *DatabaseRef) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*DatabaseRef_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isDatabaseRef_Identifier interface {
	isDatabaseRef_Identifier()
}

type DatabaseRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type DatabaseRef_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*DatabaseRef_Id) isDatabaseRef_Identifier() {}

func (*DatabaseRef_Name) isDatabaseRef_Identifier() {}

var File_common_api_proto protoreflect.FileDescriptor

const file_common_api_proto_rawDesc = "" +
	"\n" +
	"\x10common_api.proto\x12\aberserk\"C\n" +
	"\vDatabaseRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04nameB\f\n" +
	"\n" +
	"identifierB8Z6github.com/berserkdb/berserk-client-go/proto/berserkpbb\x06proto3"

var (
	file_common_api_proto_rawDescOnce sync.Once
	file_common_api_proto_rawDescData []byte
)

func file_common_api_proto_rawDescGZIP() []byte {
	file_common_api_proto_rawDescOnce.Do(func() {
		file_common_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_api_proto_rawDesc), len(file_common_api_proto_rawDesc)))
	})
	return file_common_api_proto_rawDescData
}

var file_common_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_api_proto_goTypes = []any{
	(*DatabaseRef)(nil), // 0: berserk.DatabaseRef
}
var file_common_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_api_proto_init() }
func file_common_api_proto_init() {
	if File_common_api_proto != nil {
		return
	}
	file_common_api_proto_msgTypes[0].OneofWrappers = []any{
		(*DatabaseRef_Id)(nil),
		(*DatabaseRef_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_api_proto_rawDesc), len(file_common_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_api_proto_goTypes,
		DependencyIndexes: file_common_api_proto_depIdxs,
		MessageInfos:      file_common_api_proto_msgTypes,
	}.Build()
	File_common_api_proto = out.File
	file_common_api_proto_goTypes = nil
	file_common_api_proto_depIdxs = nil
}
