// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: dynamic_value.proto

package berserkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A dynamically-typed value that can represent any BQL scalar, array, or property bag.
// Used as the cell type in query result rows — each cell in a ValueRow is a BqlValue.
type BqlValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*BqlValue_NullValue
	//	*BqlValue_RealValue
	//	*BqlValue_LongValue
	//	*BqlValue_IntValue
	//	*BqlValue_StringValue
	//	*BqlValue_BoolValue
	//	*BqlValue_TimespanValue
	//	*BqlValue_DatetimeValue
	//	*BqlValue_BagValue
	//	*BqlValue_ArrayValue
	Value         isBqlValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BqlValue) Reset() {
	*x = BqlValue{}
	mi := &file_dynamic_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BqlValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqlValue) ProtoMessage() {}

func (x *BqlValue) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqlValue.ProtoReflect.Descriptor instead.
func (*BqlValue) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{0}
}

func (x *BqlValue) GetValue() isBqlValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BqlValue) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

func (x *BqlValue) GetRealValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_RealValue); ok {
			return x.RealValue
		}
	}
	return 0
}

func (x *BqlValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *BqlValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *BqlValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *BqlValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *BqlValue) GetTimespanValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_TimespanValue); ok {
			return x.TimespanValue
		}
	}
	return 0
}

func (x *BqlValue) GetDatetimeValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return 0
}

func (x *BqlValue) GetBagValue() *PropertyBag {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_BagValue); ok {
			return x.BagValue
		}
	}
	return nil
}

func (x *BqlValue) GetArrayValue() *Array {
	if x != nil {
		if x, ok := x.Value.(*BqlValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

type isBqlValue_Value interface {
	isBqlValue_Value()
}

type BqlValue_NullValue struct {
	// Null (absent value). The bool payload is always true; the field's presence indicates null.
	NullValue bool `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type BqlValue_RealValue struct {
	// 64-bit IEEE 754 floating-point number (BQL `real` type).
	RealValue float64 `protobuf:"fixed64,2,opt,name=real_value,json=realValue,proto3,oneof"`
}

type BqlValue_LongValue struct {
	// 64-bit signed integer (BQL `long` type).
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type BqlValue_IntValue struct {
	// 32-bit signed integer (BQL `int` type).
	IntValue int32 `protobuf:"varint,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type BqlValue_StringValue struct {
	// UTF-8 string (BQL `string` type). Also used for `guid` values.
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type BqlValue_BoolValue struct {
	// Boolean (BQL `bool` type).
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type BqlValue_TimespanValue struct {
	// Duration in ticks — each tick is 100 nanoseconds (BQL `timespan` type).
	TimespanValue uint64 `protobuf:"varint,7,opt,name=timespan_value,json=timespanValue,proto3,oneof"`
}

type BqlValue_DatetimeValue struct {
	// Timestamp in ticks since 0001-01-01T00:00:00Z — each tick is 100 nanoseconds (BQL `datetime` type).
	DatetimeValue uint64 `protobuf:"varint,10,opt,name=datetime_value,json=datetimeValue,proto3,oneof"`
}

type BqlValue_BagValue struct {
	// Nested key-value map (BQL `dynamic` property bag).
	BagValue *PropertyBag `protobuf:"bytes,8,opt,name=bag_value,json=bagValue,proto3,oneof"`
}

type BqlValue_ArrayValue struct {
	// Ordered list of dynamic values (BQL `dynamic` array).
	ArrayValue *Array `protobuf:"bytes,9,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

func (*BqlValue_NullValue) isBqlValue_Value() {}

func (*BqlValue_RealValue) isBqlValue_Value() {}

func (*BqlValue_LongValue) isBqlValue_Value() {}

func (*BqlValue_IntValue) isBqlValue_Value() {}

func (*BqlValue_StringValue) isBqlValue_Value() {}

func (*BqlValue_BoolValue) isBqlValue_Value() {}

func (*BqlValue_TimespanValue) isBqlValue_Value() {}

func (*BqlValue_DatetimeValue) isBqlValue_Value() {}

func (*BqlValue_BagValue) isBqlValue_Value() {}

func (*BqlValue_ArrayValue) isBqlValue_Value() {}

// An unordered map of string keys to dynamic values.
// Represents the property-bag variant of BQL's `dynamic` type.
type PropertyBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    map[string]*BqlValue   `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyBag) Reset() {
	*x = PropertyBag{}
	mi := &file_dynamic_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyBag) ProtoMessage() {}

func (x *PropertyBag) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyBag.ProtoReflect.Descriptor instead.
func (*PropertyBag) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyBag) GetProperties() map[string]*BqlValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

// An ordered list of dynamic values.
// Represents the array variant of BQL's `dynamic` type.
type Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*BqlValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array) Reset() {
	*x = Array{}
	mi := &file_dynamic_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_dynamic_value_proto_rawDescGZIP(), []int{2}
}

func (x *Array) GetValues() []*BqlValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_dynamic_value_proto protoreflect.FileDescriptor

const file_dynamic_value_proto_rawDesc = "" +
	"\n" +
	"\x13dynamic_value.proto\x12\aberserk\"\x95\x03\n" +
	"\bBqlValue\x12\x1f\n" +
	"\n" +
	"null_value\x18\x01 \x01(\bH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"real_value\x18\x02 \x01(\x01H\x00R\trealValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x03 \x01(\x03H\x00R\tlongValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12'\n" +
	"\x0etimespan_value\x18\a \x01(\x04H\x00R\rtimespanValue\x12'\n" +
	"\x0edatetime_value\x18\n" +
	" \x01(\x04H\x00R\rdatetimeValue\x123\n" +
	"\tbag_value\x18\b \x01(\v2\x14.berserk.PropertyBagH\x00R\bbagValue\x121\n" +
	"\varray_value\x18\t \x01(\v2\x0e.berserk.ArrayH\x00R\n" +
	"arrayValueB\a\n" +
	"\x05value\"\xa5\x01\n" +
	"\vPropertyBag\x12D\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2$.berserk.PropertyBag.PropertiesEntryR\n" +
	"properties\x1aP\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.berserk.BqlValueR\x05value:\x028\x01\"2\n" +
	"\x05Array\x12)\n" +
	"\x06values\x18\x01 \x03(\v2\x11.berserk.BqlValueR\x06valuesB8Z6github.com/berserkdb/berserk-client-go/proto/berserkpbb\x06proto3"

var (
	file_dynamic_value_proto_rawDescOnce sync.Once
	file_dynamic_value_proto_rawDescData []byte
)

func file_dynamic_value_proto_rawDescGZIP() []byte {
	file_dynamic_value_proto_rawDescOnce.Do(func() {
		file_dynamic_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)))
	})
	return file_dynamic_value_proto_rawDescData
}

var file_dynamic_value_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dynamic_value_proto_goTypes = []any{
	(*BqlValue)(nil),    // 0: berserk.BqlValue
	(*PropertyBag)(nil), // 1: berserk.PropertyBag
	(*Array)(nil),       // 2: berserk.Array
	nil,                 // 3: berserk.PropertyBag.PropertiesEntry
}
var file_dynamic_value_proto_depIdxs = []int32{
	1, // 0: berserk.BqlValue.bag_value:type_name -> berserk.PropertyBag
	2, // 1: berserk.BqlValue.array_value:type_name -> berserk.Array
	3, // 2: berserk.PropertyBag.properties:type_name -> berserk.PropertyBag.PropertiesEntry
	0, // 3: berserk.Array.values:type_name -> berserk.BqlValue
	0, // 4: berserk.PropertyBag.PropertiesEntry.value:type_name -> berserk.BqlValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dynamic_value_proto_init() }
func file_dynamic_value_proto_init() {
	if File_dynamic_value_proto != nil {
		return
	}
	file_dynamic_value_proto_msgTypes[0].OneofWrappers = []any{
		(*BqlValue_NullValue)(nil),
		(*BqlValue_RealValue)(nil),
		(*BqlValue_LongValue)(nil),
		(*BqlValue_IntValue)(nil),
		(*BqlValue_StringValue)(nil),
		(*BqlValue_BoolValue)(nil),
		(*BqlValue_TimespanValue)(nil),
		(*BqlValue_DatetimeValue)(nil),
		(*BqlValue_BagValue)(nil),
		(*BqlValue_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamic_value_proto_rawDesc), len(file_dynamic_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynamic_value_proto_goTypes,
		DependencyIndexes: file_dynamic_value_proto_depIdxs,
		MessageInfos:      file_dynamic_value_proto_msgTypes,
	}.Build()
	File_dynamic_value_proto = out.File
	file_dynamic_value_proto_goTypes = nil
	file_dynamic_value_proto_depIdxs = nil
}
